name: todo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  cloud_functions: ^3.2.9
  cupertino_icons: ^0.1.2
  firebase_auth: ^3.3.4
  firebase_core: ^1.12.0
  firebase_database: ^9.0.8
  firebase_messaging: ^11.2.6
  firebase_storage: ^10.2.4
  flutter:
    sdk: flutter
  image: ^2.1.12
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  mdi: ^4.0.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - img/camera.png
